### ISSUE TITLE
Applet Generic Error when reading newly issued EID cards.

### ISSUE THREAD

**Issue by Shravya89** [janvdbergh/eid-applet#101]
Hi All,

We are using eid-applet-package-2.0.0.FEDICT.jar in our application to read data from the EID card.
Now for the newly issued cards we are getting error when trying to read the data.

PFB the error - 

eID Applet - Copyright (C) 2008-2013 FedICT.

Copyright (C) 2014-2015 e-Contract.be BVBA.

Released under GNU LGPL version 3.0 license.

More info: https://github.com/Fedict/eid-applet

checking applet privileges...

security manager permission check for java 1.6...

checking web application trust...

running privileged code...

OS is [Windows 7]. Not Enabling PCSC library fix.

eID browser applet version: 2.0.0.FEDICT

Java version: 1.8.0_112

Java vendor: Oracle Corporation

OS: Windows 7

OS version: 6.1

OS arch: x86

Current time: Thu Dec 15 13:56:14 CET 2016

session cookie detected

sending message: HelloMessage

current protocol state: null

protocol state transition: INIT

SSL handshake finish cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

response message: IdentificationRequestMessage

current protocol state: INIT

protocol state transition: IDENTIFY

include address: true

include photo: true

include integrity data: false

include certificates: true

remove card: true

identity data usage: null

Detecting eID card...

Please insert your eID card...

Scanning card terminal: VASCO DP905v1.1 0

eID card detected in card terminal : VASCO DP905v1.1 0

Reading out identity...

Reading identity file...

selecting file

read binary

Size identity file: 176

Read address file...

selecting file

read binary

Size address file: 121

Read photo file...

selecting file

read binary

reading authn certificate file...

selecting file

read binary

size authn cert file: 1900

reading sign certificate file...

selecting file

read binary

size non-repud cert file: 1900

reading citizen CA certificate file...

selecting file

read binary

size Cit CA cert file: 1556

reading root certificate file...

selecting file

read binary

size Root CA cert file: 1426

Please remove your eID card.

Transmitting identity data...

sending message: IdentityDataMessage

current protocol state: IDENTIFY

SSL handshake finish cipher suite: TLS_DHE_RSA_WITH_AES_128_GCM_SHA256

HTTP response code: 500

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">

<HTML>

<HEAD>

<TITLE>Error 500--Internal Server Error</TITLE>

<META NAME="GENERATOR" CONTENT="WebLogic Server">

</HEAD>

<BODY bgcolor="white">

<FONT FACE=Helvetica><BR CLEAR=all>

<TABLE border=0 cellspacing=5><TR><TD><BR CLEAR=all>

<FONT FACE="Helvetica" COLOR="black" SIZE="3"><H2>Error 500--Internal Server Error</H2>

</FONT></TD></TR>

</TABLE>

<TABLE border=0 width=100% cellpadding=10><TR><TD VALIGN=top WIDTH=100% BGCOLOR=white><FONT FACE="Courier New"><pre>javax.servlet.ServletException: photo digest incorrect

                at be.fedict.eid.applet.service.impl.handler.IdentityDataMessageHandler.handleMessage(IdentityDataMessageHandler.java:236)

                at be.fedict.eid.applet.service.impl.handler.IdentityDataMessageHandler.handleMessage(IdentityDataMessageHandler.java:64)

                at be.fedict.eid.applet.service.AppletServiceServlet.doPost(AppletServiceServlet.java:310)

                at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)

                at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)

                at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:226)

                at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:124)

                at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:283)

                at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:175)

                at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3395)

                at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)

                at weblogic.security.service.SecurityManager.runAs(Unknown Source)

                at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2140)

                at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2046)

                at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1366)

                at weblogic.work.ExecuteThread.execute(ExecuteThread.java:200)

                at weblogic.work.ExecuteThread.run(ExecuteThread.java:172)

</pre></FONT></TD></TR>

</TABLE>

 

</BODY>

</HTML>

error: error sending message to service. HTTP status code: 500

error type: java.io.IOException

at be.fedict.eid.applet.Controller.sendMessage:193

at be.fedict.eid.applet.Controller.sendMessage:153

at be.fedict.eid.applet.Controller.performEidIdentificationOperation:1194

at be.fedict.eid.applet.Controller.run:326

at be.fedict.eid.applet.Applet$AppletThread$1.run:595

at java.security.AccessController.doPrivileged:-2

at be.fedict.eid.applet.Applet$AppletThread.run:591

at java.lang.Thread.run:-1

Generic Error.

We are currently using the jar 2.0.0.FEDICT.jar.
Will the jars be updated?

Kr,
Shravya

**Comment by janvdbergh** [comment]
Hi @Shravya89. What version of the eid-applet-service are you using on your back-end? The photo digest is checked on the server and not in the eid-applet itself.

**Comment by Shravya89** [comment]
We are using eid-applet-service-1.0.4.GA.

**Comment by janvdbergh** [comment]
Then that will be the problem. The support for SHA2 hashes was introduced in version 1.1.0.RC3. 

I suggest you upgrade your backend to version 2.0.0.FEDICT as well if possible. This version has some breaking changes so it might not be possible to do so. In that case use version 1.1.4.

Both artifacts are available in the eID maven repository at https://maven.eid.belgium.be/.

**Comment by Shravya89** [comment]
We got the certificate revocation error so we upgraded backend to verison 2.0.0.FEDICT.
So we are using 2.0.0.FEDICT.
DO we upgrade eid-applet-service-1.0.4.GA?

**Comment by janvdbergh** [comment]
That is correct. Use version 2.0.0.FEDICT there as well.

**Comment by Shravya89** [comment]
Ok

So we should use eid-applet-service-2.0.0.FEDICT.jar and eid-applet-package-2.0.0.FEDICT.jar right?

**Comment by janvdbergh** [comment]
Yes, you can see eid-applet-package as the client part and eid-applet-service as the server part of eid-applet. You have to use the same version of both: they use a specific protocol to communicate.

**Comment by Shravya89** [comment]
Thanks.. :)
I replaced the jars with 2.0.0, but on our server we have java version "1.5.0_22" and it is throwing bad version in .class file,
This issue is because the latest EID jar has been compiled with other version of java i guess.
Can we get the jars compiled with lower version of java.

**Comment by Shravya89** [comment]
The updated jars are not compatible with the java version on our server
And could you tell me the name of the java file where we can check the support for SHA2 introduced.
As I decompiled IdentityDataMessageHandler i could not see the new algo added.

**Comment by Shravya89** [comment]
I tried running my application using the version 1.1.4.


Got the below error - 
 eID Applet - Copyright (C) 2008-2013 FedICT.
Copyright (C) 2014-2015 e-Contract.be BVBA.
Released under GNU LGPL version 3.0 license.
More info: https://github.com/Fedict/eid-applet
checking applet privileges...
security manager permission check for java 1.6...
checking web application trust...
running privileged code...
OS is [Windows 7]. Not Enabling PCSC library fix.
eID browser applet version: 2.0.0.FEDICT
Java version: 1.8.0_51
Java vendor: Oracle Corporation
OS: Windows 7
OS version: 6.1
OS arch: x86
Web application URL: https://epnyweb1int2.kpno.be/epiphany/app/service.ctrl?JSP_REQUEST=true&FILE=nonmodalpopup.jsp
Current time: Wed Dec 28 15:27:29 CET 2016
session cookie detected
sending message: HelloMessage
current protocol state: null
protocol state transition: INIT
SSL handshake finish cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA
response message: IdentificationRequestMessage
current protocol state: INIT
protocol state transition: IDENTIFY
include address: true
include photo: true
include integrity data: false
include certificates: true
remove card: true
identity data usage: null
Detecting eID card...
Please insert your eID card...
Scanning card terminal: VASCO DP905v1.1 0
eID card detected in card terminal : VASCO DP905v1.1 0
Reading out identity...
Reading identity file...
selecting file
read binary
Size identity file: 185
Read address file...
selecting file
read binary
Size address file: 121
Read photo file...
selecting file
read binary
reading authn certificate file...
selecting file
read binary
size authn cert file: 1900
reading sign certificate file...
selecting file
read binary
size non-repud cert file: 1900
reading citizen CA certificate file...
selecting file
read binary
size Cit CA cert file: 1558
reading root certificate file...
selecting file
read binary
size Root CA cert file: 1426
Please remove your eID card.
Transmitting identity data...
sending message: IdentityDataMessage
current protocol state: IDENTIFY
SSL handshake finish cipher suite: TLS_RSA_WITH_AES_128_CBC_SHA
HTTP response code: 500
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Draft//EN">
<HTML>
<HEAD>
<TITLE>Error 500--Internal Server Error</TITLE>
<META NAME="GENERATOR" CONTENT="WebLogic Server">
</HEAD>
<BODY bgcolor="white">
<FONT FACE=Helvetica><BR CLEAR=all>
<TABLE border=0 cellspacing=5><TR><TD><BR CLEAR=all>
<FONT FACE="Helvetica" COLOR="black" SIZE="3"><H2>Error 500--Internal Server Error</H2>
</FONT></TD></TR>
</TABLE>
<TABLE border=0 width=100% cellpadding=10><TR><TD VALIGN=top WIDTH=100% BGCOLOR=white><FONT FACE="Courier New"><pre>java.lang.NoSuchMethodError: java.lang.String.isEmpty&#40;&#41;Z
                at be.fedict.eid.applet.service.SpecialOrganisation.toSpecialOrganisation(SpecialOrganisation.java:69)
                at be.fedict.eid.applet.service.impl.tlv.SpecialOrganisationConvertor.convert(SpecialOrganisationConvertor.java:52)
                at be.fedict.eid.applet.service.impl.tlv.SpecialOrganisationConvertor.convert(SpecialOrganisationConvertor.java:34)
                at be.fedict.eid.applet.service.impl.tlv.TlvParser.parseThrowing(TlvParser.java:117)
                at be.fedict.eid.applet.service.impl.tlv.TlvParser.parse(TlvParser.java:56)
                at be.fedict.eid.applet.service.impl.handler.IdentityDataMessageHandler.handleMessage(IdentityDataMessageHandler.java:129)
                at be.fedict.eid.applet.service.impl.handler.IdentityDataMessageHandler.handleMessage(IdentityDataMessageHandler.java:72)
                at be.fedict.eid.applet.service.AppletServiceServlet.doPost(AppletServiceServlet.java:311)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
                at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:226)
                at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:124)
                at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:283)
                at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:175)
                at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3395)
                at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
                at weblogic.security.service.SecurityManager.runAs(Unknown Source)
                at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2140)
                at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2046)
                at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1366)
                at weblogic.work.ExecuteThread.execute(ExecuteThread.java:200)
                at weblogic.work.ExecuteThread.run(ExecuteThread.java:172)
</pre></FONT></TD></TR>
</TABLE>
</BODY>
</HTML>
error: error sending message to service. HTTP status code: 500
error type: java.io.IOException
at be.fedict.eid.applet.Controller.sendMessage:193
at be.fedict.eid.applet.Controller.sendMessage:153
at be.fedict.eid.applet.Controller.performEidIdentificationOperation:1194
at be.fedict.eid.applet.Controller.run:326
at be.fedict.eid.applet.Applet$AppletThread$1.run:595
at java.security.AccessController.doPrivileged:-2
at be.fedict.eid.applet.Applet$AppletThread.run:591
at java.lang.Thread.run:-1
Generic Error.

**Comment by janvdbergh** [comment]
The isEmpty() method was added to java.lang.String in Java 6, which means it is not available in your JRE. 

Is it possible for you to upgrade to a more recent Java version? (Java 5 is no longer supported by Oracle as well.)

**Comment by Shravya89** [comment]
No It is not possible. We have connectivity with others systems as well so it will be difficult to upgrade

Can we just get a fix for the photo digest error in the current jar that we are using.

**Comment by janvdbergh** [comment]
I have discussed this internally and we no longer support Java 5. Our code base was switched to Java 6 some years ago.

Since the source code is open, feel free to create your own build of eid-applet-service with a Java 5 compiler. It is best to start from the tag 2.0.0.FEDICT and make the necessary changes from there.
